insert into CandidateLists (Year, Number, Name) values (1994, 1, 'Občanská demokratická strana');
insert into CandidateLists (Year, Number, Name) values (1994, 2, 'Sdružení ČSSD, LSU, SZ, NK');
insert into CandidateLists (Year, Number, Name) values (1994, 3, 'Sdružení KSČM, SDL, NK');
insert into CandidateLists (Year, Number, Name) values (1994, 4, 'Sdružení nezávislých kandidátů');
insert into CandidateLists (Year, Number, Name) values (1994, 5, 'Křesťan.a demokrat.unie-Českosl.strana lidová');

insert into CandidateLists (Year, Number, Name) values (1998, 1, 'Sdružení nezávislých kandidátů - místní sdružení celkem');
insert into CandidateLists (Year, Number, Name) values (1998, 2, 'Sdružení nezávislých kandidátů - místní sdružení celkem');
insert into CandidateLists (Year, Number, Name) values (1998, 3, 'Sdružení nezávislých kandidátů - místní sdružení celkem');
insert into CandidateLists (Year, Number, Name) values (1998, 4, 'Občanská demokratická strana');
insert into CandidateLists (Year, Number, Name) values (1998, 5, 'Křesťanská a demokratická unie - Československá strana lidová');
insert into CandidateLists (Year, Number, Name) values (1998, 6, 'Česká strana sociálně demokratická');
insert into CandidateLists (Year, Number, Name) values (1998, 7, 'Komunistická strana Čech a Moravy');

insert into CandidateLists (Year, Number, Name) values (2002, 1, 'Česká strana sociálně demokratická');
insert into CandidateLists (Year, Number, Name) values (2002, 2, 'Křesťanská a demokratická unie - Československá strana lidová');
insert into CandidateLists (Year, Number, Name) values (2002, 3, 'Komunistická strana Čech a Moravy');
insert into CandidateLists (Year, Number, Name) values (2002, 4, 'Občanská demokratická strana');
insert into CandidateLists (Year, Number, Name) values (2002, 5, 'Sdružení nezávislých kandidátů - Sportovci pro Přibyslav');
insert into CandidateLists (Year, Number, Name) values (2002, 6, 'Sdružení nezávislých kandidátů - NÁŠ DOMOV');
insert into CandidateLists (Year, Number, Name) values (2002, 7, 'Sdružení nezávislých kandidátů - ŠANCE PRO KAŽDÉHO');
insert into CandidateLists (Year, Number, Name) values (2002, 8, 'Sdružení nezávislých kandidátů - NEZÁVISLÍ');

insert into CandidateLists (Year, Number, Name) values (2006, 1, 'Občanská demokratická strana');
insert into CandidateLists (Year, Number, Name) values (2006, 2, 'Sdružení nezávislých kandidátů - Přibyslav');
insert into CandidateLists (Year, Number, Name) values (2006, 3, 'Komunistická strana Čech a Moravy');
insert into CandidateLists (Year, Number, Name) values (2006, 4, 'Česká strana sociálně demokratická');
insert into CandidateLists (Year, Number, Name) values (2006, 5, 'Křesťanská a demokratická unie - Československá strana lidová');

insert into CandidateLists (Year, Number, Name) values (2010, 1, 'NEZÁVISLÍ PRO PŘIBYSLAV');
insert into CandidateLists (Year, Number, Name) values (2010, 2, 'Komunistická strana Čech a Moravy');
insert into CandidateLists (Year, Number, Name) values (2010, 3, 'Sdružení nezávislých kandidátů Přibyslav');
insert into CandidateLists (Year, Number, Name) values (2010, 4, 'Křesťanská a demokratická unie - Československá strana lidová');
insert into CandidateLists (Year, Number, Name) values (2010, 5, 'Česká strana sociálně demokratická');
insert into CandidateLists (Year, Number, Name) values (2010, 6, 'Občanská demokratická strana');

insert into CandidateLists (Year, Number, Name) values (2014, 1, 'Komunistická strana Čech a Moravy');
insert into CandidateLists (Year, Number, Name) values (2014, 2, 'Křesťanská a demokratická unie - Československá strana lidová');
insert into CandidateLists (Year, Number, Name) values (2014, 3, 'NEZÁVISLÍ PRO PŘIBYSLAV');
insert into CandidateLists (Year, Number, Name) values (2014, 4, 'Občanská demokratická strana');
insert into CandidateLists (Year, Number, Name) values (2014, 5, 'ANO 2011');
insert into CandidateLists (Year, Number, Name) values (2014, 6, 'PŘIBYSLAV 2014');
insert into CandidateLists (Year, Number, Name) values (2014, 7, 'Česká strana sociálně demokratická');

/* výsledky */
update CandidateLists set TotalVotes=8867, Mandates=4 where Year=1994 and Number=1;
update CandidateLists set TotalVotes=3686, Mandates=2 where Year=1994 and Number=2;
update CandidateLists set TotalVotes=5829, Mandates=3 where Year=1994 and Number=3;
update CandidateLists set TotalVotes=5901, Mandates=3 where Year=1994 and Number=4;
update CandidateLists set TotalVotes=5930, Mandates=3 where Year=1994 and Number=5;
update CandidateLists set TotalVotes=2371, Mandates=1 where Year=1998 and Number=1;
update CandidateLists set TotalVotes=2471, Mandates=1 where Year=1998 and Number=2;
update CandidateLists set TotalVotes=2697, Mandates=2 where Year=1998 and Number=3;
update CandidateLists set TotalVotes=5368, Mandates=3 where Year=1998 and Number=4;
update CandidateLists set TotalVotes=4741, Mandates=3 where Year=1998 and Number=5;
update CandidateLists set TotalVotes=4364, Mandates=3 where Year=1998 and Number=6;
update CandidateLists set TotalVotes=3464, Mandates=2 where Year=1998 and Number=7;
update CandidateLists set TotalVotes=3614, Mandates=2 where Year=2002 and Number=1;
update CandidateLists set TotalVotes=3651, Mandates=3 where Year=2002 and Number=2;
update CandidateLists set TotalVotes=3194, Mandates=2 where Year=2002 and Number=3;
update CandidateLists set TotalVotes=6136, Mandates=5 where Year=2002 and Number=4;
update CandidateLists set TotalVotes=2090, Mandates=1 where Year=2002 and Number=5;
update CandidateLists set TotalVotes=2155, Mandates=1 where Year=2002 and Number=6;
update CandidateLists set TotalVotes=1197, Mandates=0 where Year=2002 and Number=7;
update CandidateLists set TotalVotes=2283, Mandates=1 where Year=2002 and Number=8;
update CandidateLists set TotalVotes=6308, Mandates=4 where Year=2006 and Number=1;
update CandidateLists set TotalVotes=4481, Mandates=3 where Year=2006 and Number=2;
update CandidateLists set TotalVotes=2946, Mandates=2 where Year=2006 and Number=3;
update CandidateLists set TotalVotes=4038, Mandates=3 where Year=2006 and Number=4;
update CandidateLists set TotalVotes=4185, Mandates=3 where Year=2006 and Number=5;
update CandidateLists set TotalVotes=4159, Mandates=3 where Year=2010 and Number=1;
update CandidateLists set TotalVotes=2339, Mandates=1 where Year=2010 and Number=2;
update CandidateLists set TotalVotes=3456, Mandates=2 where Year=2010 and Number=3;
update CandidateLists set TotalVotes=3673, Mandates=2 where Year=2010 and Number=4;
update CandidateLists set TotalVotes=4249, Mandates=3 where Year=2010 and Number=5;
update CandidateLists set TotalVotes=5860, Mandates=4 where Year=2010 and Number=6;
update CandidateLists set TotalVotes=2112, Mandates=1 where Year=2014 and Number=1;
update CandidateLists set TotalVotes=3945, Mandates=3 where Year=2014 and Number=2;
update CandidateLists set TotalVotes=3243, Mandates=2 where Year=2014 and Number=3;
update CandidateLists set TotalVotes=4730, Mandates=3 where Year=2014 and Number=4;
update CandidateLists set TotalVotes=2374, Mandates=2 where Year=2014 and Number=5;
update CandidateLists set TotalVotes=3228, Mandates=2 where Year=2014 and Number=6;
update CandidateLists set TotalVotes=3351, Mandates=2 where Year=2014 and Number=7;
